// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkgmgxnfodtxzezzmxxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrZ21neG5mb2R0eHplenpteHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Mjg3MjksImV4cCI6MjA3MDIwNDcyOX0.zEUWdPzpvg6gE2jy3E_9Dj1EGp_TJFPBR1JdaUhbCrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});